version: 2

project_name: tunneller

before:
  hooks:
    - go mod tidy

builds:
  - id: tunneller
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goarch:
      - amd64
      - arm64
    goos:
      - linux
    main: ./...
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w
    tags:
      - netgo

archives:
  - allow_different_binary_count: true
    formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  use: github-native

checksum:
  name_template: "checksums.txt"

release:
  draft: false
  make_latest: true
  replace_existing_artifacts: true
  prerelease: auto

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

sboms:
  - id: package
    artifacts: package
    disable: false
  - artifacts: archive
    disable: false

dockers_v2:
  - images:
      - ghcr.io/andrewheberle/tunneller
    ids:
      - tunneller
    tags:
      - "v{{ .Version }}"
      - "{{ if not .IsSnapshot }}latest{{ end }}"
    labels:
      "org.opencontainers.image.description": "SSH Tunneller Reverse Proxy"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    annotations:
      "org.opencontainers.image.description": "SSH Tunneller Reverse Proxy"
    platforms:
      - linux/amd64
      - linux/arm64

docker_digest:
  name_template: "digests.txt"

docker_signs:
  - cmd: cosign
    output: true
    args:
      - "sign"
      - "${artifact}@${digest}"
      - "--yes"
